layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_slides"
    values:
      layout: "iframe"

collections:
  slides:
    output: true

social_media:
  linkedin: developeranubha
  twitter: AnubhaKushwaha1
  leetcode: anubhakushwaha